# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Engineering time tracking and local session context
exec-once = /home/zyk3l/.config/hypr/custom/scripts/start_co2_work_companion.sh
