# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

##! Apps
bind = Super, Return, exec, kitty -1 # Terminal
bind = Super, E, exec, dolphin # File manager
bind = Super, W, exec, /home/zyk3l/.local/bin/google-chrome-stable # Browser
bind = Super, C, exec, /usr/bin/code # Code editor
bind = Super, I, exec, ~/.config/hypr/custom/scripts/toggle-shell-settings.sh # Settings app
bind = Ctrl+Shift, Escape, exec, kitty -1 fish -c btop # Task manager
unbind = Super, BracketLeft
bind = Super, BracketLeft, exec, qs -c $qsConfig ipc call pixelSprout toggle # Toggle Pixel Sprout

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above
